# Generated by Django 3.0.7 on 2020-06-23 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20200619_1833'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='course',
        ),
        migrations.AddField(
            model_name='order',
            name='courses',
            field=models.ManyToManyField(to='myapp.Course'),
        ),
    ]
