# Generated by Django 3.0.7 on 2020-07-21 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20200721_1353'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='stage',
            new_name='stages',
        ),
    ]
