# Generated by Django 3.0.7 on 2020-07-21 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20200721_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='stages',
            field=models.PositiveIntegerField(default=3),
        ),
    ]
