# Generated by Django 3.0.7 on 2020-08-02 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20200721_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='hours',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
